import { createSlice } from "@reduxjs/toolkit";
const initialState = {
  value: [
    {
      id: 1700000000001,
      title: "The Silent Ocean",
      author: "Rachel Morgan",
      description:
        "A deep dive into the mysteries of the sea, blending fact with fiction to uncover the wonders of the ocean.",
      rating: 4.5,
      category: "Fiction",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹499",
    },
    {
      id: 1700000000002,
      title: "Quantum Dreams",
      author: "Elijah Wright",
      description:
        "A Sci-Fi exploration of parallel worlds, quantum physics, and the possibilities that lie within alternate realities.",
      rating: 4.8,
      category: "Sci-Fi",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹599",
    },
    {
      id: 1700000000003,
      title: "Unbreakable Bonds",
      author: "Sophia Bennett",
      description:
        "A touching novel about the relationships that define us and the strength we find in family and friendship.",
      rating: 4.2,
      category: "Fiction",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹399",
    },
    {
      id: 1700000000004,
      title: "The Entrepreneur's Handbook",
      author: "Daniel Rogers",
      description:
        "A comprehensive guide to building a successful business from scratch, filled with real-life examples and strategies.",
      rating: 4.7,
      category: "Non-Fiction",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹699",
    },
    {
      id: 1700000000005,
      title: "Galaxies Beyond",
      author: "Lucas Evans",
      description:
        "An intergalactic Sci-Fi adventure exploring uncharted territories and the civilizations that exist beyond our own galaxy.",
      rating: 4.6,
      category: "Sci-Fi",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹549",
    },
    {
      id: 1700000000006,
      title: "Mindful Living",
      author: "Olivia Carter",
      description:
        "A self-help book that focuses on mindfulness practices to help readers live a more balanced and fulfilling life.",
      rating: 4.3,
      category: "Self-Help",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹350",
    },
    {
      id: 1700000000007,
      title: "The Forgotten History",
      author: "Henry Patterson",
      description:
        "A compelling journey through time, uncovering forgotten historical events that shaped our world.",
      rating: 4.8,
      category: "History",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹499",
    },
    {
      id: 1700000000008,
      title: "Business Strategies for Success",
      author: "Emma Johnson",
      description:
        "A powerful guide for entrepreneurs and business owners on how to build and scale successful companies.",
      rating: 4.5,
      category: "Business",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹799",
    },
    {
      id: 1700000000009,
      title: "The Hacker’s Mind",
      author: "Nathan Clark",
      description:
        "A deep dive into the world of ethical hacking, cybersecurity, and how technology shapes our digital future.",
      rating: 4.6,
      category: "Technology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹899",
    },
    {
      id: 1700000000010,
      title: "Healthy Habits",
      author: "Laura Simmons",
      description:
        "A practical self-help guide on building sustainable health habits for a better and longer life.",
      rating: 4.4,
      category: "Health",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹399",
    },
    {
      id: 1700000000011,
      title: "Artificial Intelligence Revolution",
      author: "Michael Brooks",
      description:
        "An insightful book on how AI is changing industries and our daily lives.",
      rating: 4.7,
      category: "Technology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹999",
    },
    {
      id: 1700000000012,
      title: "The Power of Positive Thinking",
      author: "Norman Vincent Peale",
      description:
        "A timeless self-help book on how positivity can transform lives.",
      rating: 4.5,
      category: "Self-Help",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹350",
    },
    {
      id: 1700000000013,
      title: "The Lost Civilization",
      author: "Robert Matthews",
      description:
        "A historical fiction novel uncovering an ancient lost civilization and its secrets.",
      rating: 4.3,
      category: "Fiction",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹450",
    },
    {
      id: 1700000000014,
      title: "Deep Space Exploration",
      author: "Anna Foster",
      description:
        "A non-fiction book exploring the vastness of space and the future of space travel.",
      rating: 4.8,
      category: "Science",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹799",
    },
    {
      id: 1700000000015,
      title: "The Art of Coding",
      author: "James Walters",
      description:
        "A beginner-friendly guide to programming concepts and best practices.",
      rating: 4.6,
      category: "Technology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹599",
    },
    {
      id: 1700000000016,
      title: "The Psychology of Money",
      author: "Morgan Housel",
      description:
        "A deep dive into the behaviors and mindsets that shape financial decisions.",
      rating: 4.9,
      category: "Finance",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹499",
    },
    {
      id: 1700000000017,
      title: "Secrets of the Universe",
      author: "Eleanor Parker",
      description:
        "A fascinating book about the mysteries of the cosmos and our place in it.",
      rating: 4.7,
      category: "Science",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹699",
    },
    {
      id: 1700000000018,
      title: "The Road to Success",
      author: "Jonathan Reed",
      description:
        "A motivational book filled with stories of successful individuals and their journeys.",
      rating: 4.5,
      category: "Self-Help",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹399",
    },
    {
      id: 1700000000019,
      title: "The Cybersecurity Handbook",
      author: "Eric Dawson",
      description:
        "A practical guide to cybersecurity and staying safe online.",
      rating: 4.7,
      category: "Technology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹899",
    },
    {
      id: 1700000000020,
      title: "Mastering Time Management",
      author: "Helen Grant",
      description:
        "A self-help book focused on productivity and effective time management techniques.",
      rating: 4.4,
      category: "Self-Help",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹350",
    },
    {
      id: 1700000000021,
      title: "The Art of Negotiation",
      author: "Richard Palmer",
      description:
        "A guide to mastering negotiation skills in business and daily life.",
      rating: 4.6,
      category: "Business",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹599",
    },
    {
      id: 1700000000022,
      title: "The Green Planet",
      author: "Jessica Holt",
      description:
        "An environmental book discussing sustainability and protecting nature.",
      rating: 4.7,
      category: "Environment",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹499",
    },
    {
      id: 1700000000023,
      title: "The Untold History",
      author: "Stephen Carter",
      description:
        "A book revealing hidden and lesser-known historical events.",
      rating: 4.5,
      category: "History",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹550",
    },
    {
      id: 1700000000024,
      title: "The Digital Age",
      author: "Laura Simmons",
      description:
        "A study on how digital technology is reshaping society and industries.",
      rating: 4.8,
      category: "Technology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹750",
    },
    {
      id: 1700000000025,
      title: "The Chef’s Secret",
      author: "Daniel Roberts",
      description: "A cookbook with unique recipes from world-renowned chefs.",
      rating: 4.6,
      category: "Food",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹899",
    },
    {
      id: 1700000000026,
      title: "The Future of Transportation",
      author: "Mark Evans",
      description:
        "A detailed exploration of emerging trends in transport and mobility.",
      rating: 4.7,
      category: "Science",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹699",
    },
    {
      id: 1700000000027,
      title: "The Human Mind",
      author: "Emma Wright",
      description: "An analysis of human psychology and cognitive processes.",
      rating: 4.9,
      category: "Psychology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹499",
    },
    {
      id: 1700000000028,
      title: "The Hidden Power of Habits",
      author: "Oliver Scott",
      description:
        "A guide to developing positive habits and breaking bad ones.",
      rating: 4.5,
      category: "Self-Help",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹399",
    },
    {
      id: 1700000000029,
      title: "The Evolution of Music",
      author: "Sarah Collins",
      description:
        "A journey through the history of music and its cultural impact.",
      rating: 4.6,
      category: "Music",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹450",
    },
    {
      id: 1700000000030,
      title: "The Entrepreneur’s Journey",
      author: "William Carter",
      description:
        "An inspiring book filled with stories of entrepreneurs and their challenges.",
      rating: 4.7,
      category: "Business",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹650",
    },
    {
      id: 1707859200031,
      title: "The Art of Minimalism",
      author: "Sophia Adams",
      description:
        "A guide to living a simple, clutter-free, and meaningful life.",
      rating: 4.6,
      category: "Lifestyle",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹499",
    },
    {
      id: 1707859200032,
      title: "The Power of Focus",
      author: "Nathan Green",
      description: "Techniques to improve concentration and productivity.",
      rating: 4.8,
      category: "Self-Help",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹399",
    },
    {
      id: 1707859200033,
      title: "Cosmic Mysteries",
      author: "Liam Turner",
      description:
        "An exploration of the universe’s biggest unsolved mysteries.",
      rating: 4.7,
      category: "Science",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹599",
    },
    {
      id: 1707859200034,
      title: "The Art of Public Speaking",
      author: "Julia Henderson",
      description:
        "A step-by-step guide to mastering the skill of public speaking.",
      rating: 4.6,
      category: "Communication",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹550",
    },
    {
      id: 1707859200035,
      title: "The Science of Happiness",
      author: "Olivia Bennett",
      description:
        "A book that uncovers the secrets to a fulfilling and happy life.",
      rating: 4.9,
      category: "Psychology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹699",
    },
    {
      id: 1707859200036,
      title: "The AI Revolution",
      author: "Benjamin Clarke",
      description: "How artificial intelligence is transforming the world.",
      rating: 4.8,
      category: "Technology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹799",
    },
    {
      id: 1707859200037,
      title: "The Secret of Financial Freedom",
      author: "Daniel Harris",
      description: "Practical steps to achieve financial independence.",
      rating: 4.7,
      category: "Finance",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹650",
    },
    {
      id: 1707859200038,
      title: "Mastering Time Management",
      author: "Ella Cooper",
      description: "Effective strategies for making the most of your time.",
      rating: 4.5,
      category: "Self-Help",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹449",
    },
    {
      id: 1707859200039,
      title: "The World of Cryptocurrencies",
      author: "Matthew Evans",
      description:
        "A deep dive into Bitcoin, Ethereum, and blockchain technology.",
      rating: 4.6,
      category: "Finance",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹799",
    },
    {
      id: 1707859200040,
      title: "The Mindful Leader",
      author: "Sophia James",
      description: "How mindfulness can make you a better leader.",
      rating: 4.7,
      category: "Leadership",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹699",
    },
    {
      id: 1718207281001,
      title: "The Secrets of the Brain",
      author: "Daniel Carter",
      description:
        "Exploring the complexities of the human brain and its untapped potential.",
      rating: 4.8,
      category: "Science",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹799",
    },
    {
      id: 1718207281002,
      title: "Mastering Emotional Intelligence",
      author: "Sophia Morgan",
      description:
        "A guide to understanding and managing emotions effectively.",
      rating: 4.7,
      category: "Psychology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹699",
    },
    {
      id: 1718207281003,
      title: "The Entrepreneur’s Mindset",
      author: "Michael Anderson",
      description: "How to think and act like a successful entrepreneur.",
      rating: 4.8,
      category: "Business",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹899",
    },
    {
      id: 1718207281004,
      title: "The Evolution of Technology",
      author: "Emily Thompson",
      description: "A historical perspective on technological advancements.",
      rating: 4.7,
      category: "Technology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹799",
    },
    {
      id: 1718207281005,
      title: "The Power of Self-Discipline",
      author: "Noah Harris",
      description: "Developing habits for success through self-discipline.",
      rating: 4.9,
      category: "Self-Help",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹499",
    },
    {
      id: 1718207281006,
      title: "The Digital Age",
      author: "Lucas Mitchell",
      description:
        "How the internet and digital media have transformed society.",
      rating: 4.7,
      category: "Technology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹749",
    },
    {
      id: 1718207281007,
      title: "The Science of Decision Making",
      author: "Olivia Roberts",
      description: "Understanding the psychology behind making better choices.",
      rating: 4.8,
      category: "Psychology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹699",
    },
    {
      id: 1718207281008,
      title: "Mastering the Art of Negotiation",
      author: "Ethan Bennett",
      description:
        "Techniques to improve negotiation skills in business and life.",
      rating: 4.7,
      category: "Business",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹899",
    },
    {
      id: 1718207281009,
      title: "The Future of Work",
      author: "Sophia Turner",
      description: "How automation and AI are shaping the workplace.",
      rating: 4.6,
      category: "Technology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹799",
    },
    {
      id: 1718207281010,
      title: "The Art of Critical Thinking",
      author: "Benjamin Scott",
      description:
        "A guide to developing strong analytical and reasoning skills.",
      rating: 4.9,
      category: "Self-Help",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹599",
    },
    {
      id: 1718207281011,
      title: "The AI-Driven Economy",
      author: "Daniel Brooks",
      description: "How artificial intelligence is revolutionizing industries.",
      rating: 4.8,
      category: "Technology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹799",
    },
    {
      id: 1718207281012,
      title: "Mastering Productivity",
      author: "Emma Collins",
      description: "Proven methods to boost efficiency and get more done.",
      rating: 4.7,
      category: "Self-Help",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹499",
    },
    {
      id: 1718207281013,
      title: "The Hidden World of Finance",
      author: "William Anderson",
      description: "An inside look at how global finance works.",
      rating: 4.6,
      category: "Finance",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹899",
    },
    {
      id: 1718207281014,
      title: "The Entrepreneur’s Playbook",
      author: "Charlotte Harris",
      description:
        "Strategies for building a successful business from scratch.",
      rating: 4.8,
      category: "Business",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹799",
    },
    {
      id: 1718207281015,
      title: "The Road to Financial Freedom",
      author: "Nathan White",
      description: "A step-by-step guide to achieving financial independence.",
      rating: 4.7,
      category: "Finance",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹849",
    },
    {
      id: 1718207281016,
      title: "The Science of Habits",
      author: "David Miller",
      description: "How to build good habits and break bad ones effectively.",
      rating: 4.8,
      category: "Self-Help",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹649",
    },
    {
      id: 1718207281017,
      title: "The Creative Mind",
      author: "Lily Thompson",
      description: "Unlocking the secrets of creativity and innovation.",
      rating: 4.7,
      category: "Creativity",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹699",
    },
    {
      id: 1718207281018,
      title: "Investing for Beginners",
      author: "Jack Edwards",
      description: "A beginner's guide to smart investing and wealth building.",
      rating: 4.6,
      category: "Finance",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹749",
    },
    {
      id: 1718207281019,
      title: "The Digital Marketing Handbook",
      author: "Ava Walker",
      description: "Mastering SEO, social media, and content marketing.",
      rating: 4.9,
      category: "Business",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹799",
    },
    {
      id: 1718207281020,
      title: "Understanding Human Behavior",
      author: "Michael Carter",
      description: "Psychological insights into how people think and act.",
      rating: 4.7,
      category: "Psychology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹699",
    },
    {
      id: 1718207281021,
      title: "The Art of Mindfulness",
      author: "Samantha Green",
      description: "A guide to living in the moment and reducing stress.",
      rating: 4.8,
      category: "Self-Help",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹599",
    },
    {
      id: 1718207281022,
      title: "The Coding Masterclass",
      author: "James Wilson",
      description: "A comprehensive guide to modern programming languages.",
      rating: 4.9,
      category: "Technology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹899",
    },
    {
      id: 1718207281023,
      title: "The Future of Transportation",
      author: "Emily Adams",
      description: "How technology is revolutionizing travel and mobility.",
      rating: 4.6,
      category: "Technology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹799",
    },
    {
      id: 1718207281024,
      title: "The Psychology of Leadership",
      author: "Robert Johnson",
      description: "Key traits and strategies of effective leaders.",
      rating: 4.8,
      category: "Business",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹849",
    },
    {
      id: 1718207281025,
      title: "Mastering Personal Finance",
      author: "Sophia Lewis",
      description:
        "Smart money management tips for long-term financial success.",
      rating: 4.7,
      category: "Finance",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹749",
    },
    {
      id: 1718207281026,
      title: "The Secrets of the Universe",
      author: "Daniel Roberts",
      description: "Exploring the mysteries of space, time, and the cosmos.",
      rating: 4.9,
      category: "Science",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹899",
    },
    {
      id: 1718207281027,
      title: "Artificial Intelligence Explained",
      author: "Olivia Harris",
      description: "An in-depth look at AI and its impact on the future.",
      rating: 4.8,
      category: "Technology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹999",
    },
    {
      id: 1718207281028,
      title: "The Power of Positive Thinking",
      author: "John Maxwell",
      description: "How a positive mindset can transform your life.",
      rating: 4.7,
      category: "Self-Help",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹599",
    },
    {
      id: 1718207281029,
      title: "Entrepreneurship 101",
      author: "Grace Carter",
      description: "A step-by-step guide to building your own business.",
      rating: 4.8,
      category: "Business",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹849",
    },
    {
      id: 1718207281030,
      title: "The History of Civilization",
      author: "Henry Foster",
      description: "A journey through the rise and fall of great societies.",
      rating: 4.7,
      category: "History",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹799",
    },
    {
      id: 1718207281031,
      title: "The Science of Motivation",
      author: "Emma Collins",
      description: "Understanding what drives human behavior and success.",
      rating: 4.8,
      category: "Psychology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹699",
    },
    {
      id: 1718207281032,
      title: "Machine Learning Basics",
      author: "Andrew Reed",
      description:
        "A beginner-friendly introduction to machine learning concepts.",
      rating: 4.9,
      category: "Technology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹999",
    },
    {
      id: 1718207281033,
      title: "The Psychology of Success",
      author: "Rachel Bennett",
      description: "The mindset and habits of highly successful people.",
      rating: 4.7,
      category: "Self-Help",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹649",
    },
    {
      id: 1718207281034,
      title: "The Future of Work",
      author: "William Parker",
      description: "How technology is changing careers and the job market.",
      rating: 4.8,
      category: "Business",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹799",
    },
    {
      id: 1718207281035,
      title: "Healthy Living Made Simple",
      author: "Sophia Turner",
      description: "Practical tips for maintaining a healthy lifestyle.",
      rating: 4.6,
      category: "Health",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹599",
    },
    {
      id: 1718207281036,
      title: "Deep Space Discoveries",
      author: "Edward Mitchell",
      description:
        "Exploring the latest findings in astronomy and astrophysics.",
      rating: 4.9,
      category: "Science",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹899",
    },
    {
      id: 1718207281037,
      title: "Blockchain Revolution",
      author: "Michael Sanders",
      description:
        "How blockchain technology is reshaping industries worldwide.",
      rating: 4.8,
      category: "Technology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹999",
    },
    {
      id: 1718207281038,
      title: "Mindset Matters",
      author: "Lisa Adams",
      description:
        "How shifting your mindset can lead to greater success and happiness.",
      rating: 4.7,
      category: "Self-Help",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹599",
    },
    {
      id: 1718207281039,
      title: "Startup Success Strategies",
      author: "David Clarkson",
      description: "Proven tactics for launching and scaling a startup.",
      rating: 4.8,
      category: "Business",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹849",
    },
    {
      id: 1718207281040,
      title: "World War Chronicles",
      author: "Robert Peterson",
      description: "A detailed account of major wars that shaped history.",
      rating: 4.7,
      category: "History",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹799",
    },
    {
      id: 1718207281041,
      title: "The Neuroscience of Habits",
      author: "Dr. Samuel Harris",
      description: "Understanding how habits form and how to change them.",
      rating: 4.8,
      category: "Psychology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹699",
    },
    {
      id: 1718207281042,
      title: "Data Science Essentials",
      author: "Nathan Lee",
      description:
        "An introduction to data science, analytics, and visualization.",
      rating: 4.9,
      category: "Technology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹999",
    },
    {
      id: 1718207281043,
      title: "Emotional Intelligence Mastery",
      author: "Jessica Reynolds",
      description:
        "Developing emotional intelligence for personal and professional growth.",
      rating: 4.7,
      category: "Self-Help",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹649",
    },
    {
      id: 1718207281044,
      title: "The Gig Economy Explained",
      author: "Anthony Grant",
      description: "Understanding the rise of freelancing and remote work.",
      rating: 4.8,
      category: "Business",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹799",
    },
    {
      id: 1718207281045,
      title: "The Art of Healthy Cooking",
      author: "Catherine Brown",
      description: "Delicious and nutritious recipes for a balanced diet.",
      rating: 4.6,
      category: "Health",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹599",
    },
    {
      id: 1718207281046,
      title: "The Future of AI",
      author: "Sophia Turner",
      description:
        "Exploring artificial intelligence and its impact on society.",
      rating: 4.9,
      category: "Technology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹1,099",
    },
    {
      id: 1718207281047,
      title: "The Power of Focus",
      author: "Benjamin Carter",
      description: "Techniques to enhance concentration and productivity.",
      rating: 4.7,
      category: "Self-Help",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹649",
    },
    {
      id: 1718207281048,
      title: "Financial Freedom Blueprint",
      author: "Emma Johnson",
      description:
        "Steps to achieve financial independence and wealth building.",
      rating: 4.8,
      category: "Business",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹899",
    },
    {
      id: 1718207281049,
      title: "The Psychology of Influence",
      author: "Daniel Evans",
      description: "How persuasion and influence shape decision-making.",
      rating: 4.9,
      category: "Psychology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹799",
    },
    {
      id: 1718207281050,
      title: "The History of Civilization",
      author: "William Anderson",
      description: "A deep dive into the evolution of human societies.",
      rating: 4.7,
      category: "History",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹849",
    },
    {
      id: 1718207281051,
      title: "Mastering Digital Marketing",
      author: "Olivia Scott",
      description: "A guide to digital marketing strategies for businesses.",
      rating: 4.8,
      category: "Business",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹949",
    },
    {
      id: 1718207281052,
      title: "The Art of Mindfulness",
      author: "Grace Walker",
      description: "Practicing mindfulness for a more peaceful life.",
      rating: 4.7,
      category: "Self-Help",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹599",
    },
    {
      id: 1718207281053,
      title: "Cybersecurity Essentials",
      author: "Kevin Brooks",
      description: "Understanding online security and protecting data.",
      rating: 4.9,
      category: "Technology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹999",
    },
    {
      id: 1718207281054,
      title: "The Science of Nutrition",
      author: "Laura Green",
      description: "How diet impacts health and longevity.",
      rating: 4.8,
      category: "Health",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹699",
    },
    {
      id: 1718207281055,
      title: "Secrets of the Universe",
      author: "Jonathan Reed",
      description: "Exploring black holes, dark matter, and the cosmos.",
      rating: 4.9,
      category: "Science",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹1,099",
    },
    {
      id: 1718207281056,
      title: "The Startup Playbook",
      author: "Michael Thompson",
      description: "Essential strategies for launching and scaling startups.",
      rating: 4.8,
      category: "Business",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹899",
    },
    {
      id: 1718207281057,
      title: "The Art of Negotiation",
      author: "Rachel Adams",
      description: "Mastering the skills of negotiation and persuasion.",
      rating: 4.7,
      category: "Self-Help",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹749",
    },
    {
      id: 1718207281058,
      title: "Modern Web Development",
      author: "James Carter",
      description: "An in-depth guide to front-end and back-end development.",
      rating: 4.9,
      category: "Technology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹1,199",
    },
    {
      id: 1718207281059,
      title: "The Science of Sleep",
      author: "Emily Watson",
      description: "How sleep affects health, productivity, and well-being.",
      rating: 4.8,
      category: "Health",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹699",
    },
    {
      id: 1718207281060,
      title: "Ancient Wonders of the World",
      author: "Christopher Hall",
      description: "Exploring the greatest architectural marvels of history.",
      rating: 4.7,
      category: "History",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹799",
    },
    {
      id: 1718207281061,
      title: "The Power of Habit",
      author: "Charles Duhigg",
      description: "Understanding the psychology of habit formation.",
      rating: 4.9,
      category: "Self-Help",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹849",
    },
    {
      id: 1718207281062,
      title: "Machine Learning Explained",
      author: "David Collins",
      description:
        "An introduction to machine learning concepts and applications.",
      rating: 4.9,
      category: "Technology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹1,299",
    },
    {
      id: 1718207281063,
      title: "The Mindful Entrepreneur",
      author: "Lisa Roberts",
      description:
        "Balancing business success with mindfulness and well-being.",
      rating: 4.8,
      category: "Business",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹899",
    },
    {
      id: 1718207281064,
      title: "The Human Brain",
      author: "Steven White",
      description: "A deep dive into neuroscience and brain functionality.",
      rating: 4.9,
      category: "Science",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹999",
    },
    {
      id: 1718207281065,
      title: "Personal Finance Mastery",
      author: "Sarah Turner",
      description: "A guide to managing money and building wealth.",
      rating: 4.8,
      category: "Business",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹899",
    },
    {
      id: 1718207281066,
      title: "The Psychology of Success",
      author: "Robert Green",
      description:
        "Understanding the mindset and behaviors of highly successful people.",
      rating: 4.9,
      category: "Self-Help",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹799",
    },
    {
      id: 1718207281067,
      title: "Blockchain Revolution",
      author: "Don Tapscott & Alex Tapscott",
      description:
        "How blockchain technology is transforming the digital world.",
      rating: 4.8,
      category: "Technology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹1,299",
    },
    {
      id: 1718207281068,
      title: "Nutrition Essentials",
      author: "Laura Mitchell",
      description: "A guide to balanced nutrition and healthy eating.",
      rating: 4.7,
      category: "Health",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹699",
    },
    {
      id: 1718207281069,
      title: "The AI Advantage",
      author: "Andrew McAfee",
      description: "Leveraging artificial intelligence for business growth.",
      rating: 4.9,
      category: "Technology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹1,199",
    },
    {
      id: 1718207281070,
      title: "The History of Civilizations",
      author: "Daniel Reynolds",
      description: "Exploring the rise and fall of great civilizations.",
      rating: 4.7,
      category: "History",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹899",
    },
    {
      id: 1718207281071,
      title: "Mindfulness for Beginners",
      author: "Jon Kabat-Zinn",
      description: "A step-by-step guide to mindfulness practice.",
      rating: 4.8,
      category: "Self-Help",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹749",
    },
    {
      id: 1718207281072,
      title: "The Future of Work",
      author: "Jacob Morgan",
      description: "How AI and automation are reshaping the workforce.",
      rating: 4.9,
      category: "Business",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹999",
    },
    {
      id: 1718207281073,
      title: "The Universe in a Nutshell",
      author: "Stephen Hawking",
      description: "A brief yet profound journey through space and time.",
      rating: 4.9,
      category: "Science",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹1,099",
    },
    {
      id: 1718207281074,
      title: "The Power of Positivity",
      author: "John Maxwell",
      description: "How a positive mindset can change your life.",
      rating: 4.8,
      category: "Self-Help",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹749",
    },
    {
      id: 1718207281075,
      title: "Cybersecurity Essentials",
      author: "Mark Johnson",
      description: "Protecting yourself and your business in the digital age.",
      rating: 4.9,
      category: "Technology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹1,299",
    },
    {
      id: 1707749027000,
      title: "The Psychology of Creativity",
      author: "Eleanor Barnes",
      description:
        "Unraveling the science behind creativity and how to enhance it.",
      rating: 4.7,
      category: "Psychology",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹699",
    },
    {
      id: 1707749028000,
      title: "Mastering Negotiation",
      author: "Henry Foster",
      description:
        "Essential skills and techniques for successful deal-making.",
      rating: 4.8,
      category: "Business",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹799",
    },
    {
      id: 1707749029000,
      title: "The Quantum World",
      author: "Daniel Morgan",
      description:
        "An exploration of quantum mechanics and its mind-bending implications.",
      rating: 4.9,
      category: "Science",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹999",
    },
    {
      id: 1707749030000,
      title: "The Art of Decision Making",
      author: "Sophia Reed",
      description: "A guide to making better choices in work and life.",
      rating: 4.7,
      category: "Self-Help",
      image: "https://placehold.co/200x150?text=Book&font=roboto",
      price: "₹599",
    },
  ],
};

const BookDataSLice = createSlice({
  name: "BookData",
  initialState,
  reducers: {
    addBook: (state, action) => {
      state.value.push(action.payload);
    },
  },
});

export const { addBook } = BookDataSLice.actions;
export default BookDataSLice.reducer;
